runtime: python
env: flex
entrypoint: application.py

runtime_config:
    python_version: 3

env_variables:
  FLASK_APP: "application.py"
  FLASK_ENV: "development"
  FLASK_DEBUG: "0"
  APP_ID: "f840ecdd"
  APP_KEY: "29db7a8efc7432738a7cb46615b4a122"